# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d8dbe5503b06f637784cfe25e20aae04641c3b253e6e16debe2e2ca5dc64edd93fa412c6ba5bac580503fb3d2d83f79deb8055d57d2e95616f3273a76715f59

test:
  secret_key_base: 205d8ca070290977cf65ca3b71a1c0872fafd62f580bb94a0b63e7b5f9ff0088b9196489b50c83b31b5ccce407c11b6d6b0a10c1c834d7080dadb18beb950800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
