source 'https://rubygems.org'
source 'https://rails-assets.org' # This site is super cool!

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'
gem 'rake'

# Use postgresql as the database for Active Record
gem 'pg'

# Assets
gem 'sass-rails', '~> 4.0.0'
gem 'bootstrap-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

# Javascript
gem 'jquery-rails'
gem 'angularjs-rails'
gem 'angular-ui-router-rails'
gem 'angular-ui-bootstrap-rails'
gem 'rails-assets-angular-mocks'
gem 'underscore-rails'

# Testing
gem 'rspec-rails'
gem 'jasmine-rails'

# Rails 4 compatibility
gem 'rails-observers'
gem 'actionpack-action_caching'

gem 'net-ldap'
gem 'rubycas-client'
gem 'nokogiri'
gem 'mechanize'
